CadastroPessoas/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroPessoas.Models
{
    public class Pessoa
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} Necessário")]
        [StringLength(60, MinimumLength = 5, ErrorMessage = "{0} tamanho mínimo de 6 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "{0} Necessário")]
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DtNascimento { get; set; }

        [Required(ErrorMessage ="{0} Deve ser preenchido com M para masculino ou F para feminino")]
        [StringLength(1)]
        public string Sexo { get; set; }

        public Pessoa()
        {
        }

        public Pessoa(int id, string nome, DateTime dtNascimento, string sexo)
        {
            Id = id;
            Nome = nome;
            DtNascimento = dtNascimento;
            Sexo = sexo;
        } 
    }    
}

CadastroPessoas/Models/ViewModels/ErrorViewModel.cs
using System;

namespace CadastroPessoas.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroPessoas/Controllers/HomeController.cs
using CadastroPessoas.Models;
using CadastroPessoas.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroPessoas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroPessoas/Controllers/PessoasController.cs
using CadastroPessoas.Models;
using CadastroPessoas.Services;
using CadastroPessoas.Services.Exceptions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroPessoas.Controllers
{
    public class PessoasController : Controller
    {
        private readonly PessoaService _pessoaService;

        public PessoasController(PessoaService pessoaService)
        {
            _pessoaService = pessoaService;
        }
        public IActionResult Index()
        {
            var list = _pessoaService.FindAll();

            return View(list);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar(Pessoa pessoa)
        {
            _pessoaService.Inserir(pessoa);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _pessoaService.FindById(id.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deletar(int id)
        {
            _pessoaService.Remover(id);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _pessoaService.FindById(id.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _pessoaService.FindById(id.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar (int id, Pessoa pessoa)
        {
            if (id != pessoa.Id)
            {
                return BadRequest();
            }
            try
            {
                _pessoaService.Atualizar(pessoa);
                return RedirectToAction(nameof(Index));
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (DbConcurrencyException)
            {
                return BadRequest();
            }
        }
    }
}

CadastroPessoas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CadastroPessoas/Views/Pessoas/Criar.cshtml
@model CadastroPessoas.Models.Pessoa

@{
    ViewData["Title"] = "Criar";
}

<h2>@ViewData["Title"]</h2>

<h4>Pessoas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Nome" class="custom-control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DtNascimento" class="custom-control-label"></label>
                <input asp-for="DtNascimento" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="custom-control-label"></label>
                <input asp-for="Sexo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

CadastroPessoas/Views/Pessoas/Deletar.cshtml
@model CadastroPessoas.Models.Pessoa

@{
    ViewData["Title"] = "Deletar";
}

<h2>@ViewData["Title"]</h2>

<h3> Tem certeza que deseja deletar?</h3>

<div>
    <h4>Pessoas</h4>
    <hr />
    <dl class="list-group-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DtNascimento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DtNascimento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>

    <form asp-action="Deletar">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Deletar" class="btn btn-danger" />
        <a asp-action="Index">Voltar</a>
    </form>
</div>

CadastroPessoas/Views/Pessoas/Detalhes.cshtml
@model CadastroPessoas.Models.Pessoa;

@{
    ViewData["Title"] = "Detalhes";
}

<h2>@ViewData["Title"]</h2>

<div>
    <h4>Pessoas</h4>
    <hr />
    <dl class="list-group-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DtNascimento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DtNascimento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Index">Voltar</a>
</div>

CadastroPessoas/Views/Pessoas/Editar.cshtml
@model CadastroPessoas.Models.Pessoa

@{
    ViewData["Title"] = "Editar";
}

<h2>@ViewData["Title"]</h2>

<h4>Pessoas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="custom-control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DtNascimento" class="custom-control-label"></label>
                <input asp-for="DtNascimento" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="custom-control-label"></label>
                <input asp-for="Sexo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>

</div>

CadastroPessoas/Views/Pessoas/Index.cshtml
@model IEnumerable<CadastroPessoas.Models.Pessoa>

@{
    ViewData["Title"] = "Index";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-action="Criar" class="btn btn-primary">Criar Novo</a>
</p>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DtNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DtNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.Id">Editar</a>
                <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a>
                <a asp-action="Deletar" asp-route-id="@item.Id">Delete</a>
            </td>            
        </tr>
        
        }

    </tbody>

CadastroPessoas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroPessoas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadastroPessoas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CadastroPessoas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>